######################################################################
# Automatically generated by qmake (3.0) ?? 1. ??? 18:29:22 2013
######################################################################

QT += opengl widgets
TEMPLATE = app
TARGET = TreeBuilder
INCLUDEPATH += .

# Input
HEADERS += glwidget.h \
           mainwindow.h \
           PropertiesWidget.h \
           Tree.h \
           TreeLibIndex.h \
           TreeLibLeafProperties.h \
           TreeLibMatrix3.h \
           TreeLibOBB.h \
           TreeLibPlain.h \
           TreeLibPlain4.h \
           TreeLibVector.h \
           TreeLibVertex.h \
    newleaftypewidget.h \
    leaftype.h \
    visualeditwidget.h \
    lengthmanipulator.h \
    anglemanipulator.h \
    doublespinbox.h \
    visualeditwidgettypes.h \
    pairangleeditwidget.h \
    visualeditprocessbending.h
SOURCES += glwidget.cpp \
           main.cpp \
           mainwindow.cpp \
           PropertiesWidget.cpp \
           Tree.cpp \
           TreeLibMatrix3.cpp \
           TreeLibOBB.cpp \
           TreeLibVector.cpp \
    newleaftypewidget.cpp \
    visualeditwidget.cpp \
    doublespinbox.cpp \
    pairangleeditwidget.cpp \
    visualeditprocessbending.cpp
